### ISSUE TITLE
Name Transistor

### ISSUE THREAD

**Issue by Maxmudjon** [ArnieX/esp8266_dimmer_mqtt#1]
forgive what transistors are needed ?

**Comment by ArnieX** [comment]
Hi, I'll ask my neighbour for parts list.

**Comment by Maxmudjon** [comment]
Thank you, it would be great

**Comment by ArnieX** [comment]
Hi,

so everything is in the scheme.

The transistors are STP80NF55-06FP and BC547.

**Comment by Maxmudjon** [comment]
thanks
